### ISSUE TITLE
Fresh image build fails.  Incorrect apt dependancy: libopenssl-ruby1.9.1

### ISSUE THREAD

**Issue by cbwebdevelopment** [denibertovic/logstash-forwarder-dockerfile#6]
This is the error I'm getting on a fresh image build:

```
...
Step 4 : RUN apt-get install -y wget git golang ruby ruby-dev rubygems irb ri rdoc build-essential libopenssl-ruby1.9.1 libssl-dev zlib1g-dev
 ---> Running in e4acd94de164
Reading package lists...
Building dependency tree...
E: Unable to locate package libopenssl-ruby1.9.1
E: Couldn't find any package by regex 'libopenssl-ruby1.9.1'
```

**Comment by denibertovic** [comment]
Tnx for the report. Will look into it.

**Comment by gzoritchak** [comment]
Same here.

**Comment by outrunthewolf** [comment]
Any solutions?

**Comment by NezumiRyu** [comment]
Still Waiting...

**Comment by denibertovic** [comment]
Hi everyone, can someone confirm that the PR above does indeed fix this issue?

**Comment by NezumiRyu** [comment]
:> You don't need this package anymore
We should remove this package?

**Comment by denibertovic** [comment]
I have a half done solution....the build passes but there's still the issue with ssl certificates. Will try and look at it this weekend and see if I can get a fix up.

**Comment by NezumiRyu** [comment]
I make: 
wget http://ftp.us.debian.org/debian/pool/main/r/ruby1.9.1/libruby1.9.1_1.9.2.0-2+deb6u2_amd64.deb
wget http://ftp.us.debian.org/debian/pool/main/libf/libffi/libffi5_3.0.9-3_amd64.deb
wget http://ftp.us.debian.org/debian/pool/main/r/readline5/libreadline5_5.2-7_amd64.deb
wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl0.9.8_0.9.8o-4squeeze14_amd64.deb

Dockerfile: 
...
RUN apt-get install -y wget git golang ruby ruby-dev rubygems irb ri rdoc build-essential libssl-dev zlib1g-dev
ADD *.deb /
RUN dpkg -i *.deb
...

but i still have:
/usr/local/bin/run.sh: line 21: /opt/logstash-forwarder/bin/logstash-forwarder: No such file or directory

**Comment by denibertovic** [comment]
Hi everyone, I've pushed some changes to master that should address these issues we're seeing. The image builds, but I haven't yet had the time to test it with an actual logstash server. I suspect there will be some issues with SSL, that I will need to address further, and I have some ideas for that.

Can somebody test the current master branch and let me know if it builds for them?

**Comment by NezumiRyu** [comment]
Did i do something wrong?
docker build: ok.
docker logs:
2015/03/02 13:27:08 Failed to open config file '/opt/conf/config.json': open /opt/conf/config.json: no such file or directory

**Comment by denibertovic** [comment]
@NezumiRyu cp conf-example conf. Modify the config.json file if needed and then bind mount it to /opt/conf inside the container

**Comment by NezumiRyu** [comment]
docker run --name forwarder -d -v /tmp/feeds -v /srv/logstash-forwarder-dockerfile/certs/:/opt/certs/ -v /srv/logstash-forwarder-dockerfile/conf/:/opt/conf -e LOGSTASH_SERVER="1.2.3.4:5043" -t forwarder

a199d62d0512        forwarder:latest    "/bin/sh -c /usr/loc   2 seconds ago       Up 2 seconds                            forwarder        

Works.

**Comment by denibertovic** [comment]
Awesome. I will try and get a trusted build going on the Hub so people don't have to build the image themselves. 

I also have an idea to setup docker-compose and have one command bring up the whole ELK stack.

**Comment by outrunthewolf** [comment]
Is this an issue with ruby ssl on debian? I always have some problems with the ruby 1.9 build on ubuntu.

**Comment by denibertovic** [comment]
@outrunthewolf from what I recall it was an issue with golang 1.4 and ssl.
